import type { Trip } from "@/lib/types";

export const testTrip: Trip = {
  id: "trip-test-1",
  title: "聖水の静かな午後",
  date: "2026-08-19",
  startTime: "13:00",
  endTime: "18:00",
  budget: 80000,
  estimatedTotalCost: 12000,
  providerModes: { llm: "mock", place: "mock", crowd: "mock" },
  warnings: ["テスト用のモックデータです。"],
  stops: [
    {
      id: "stop-1",
      order: 1,
      placeId: "place-1",
      placeName: "テストカフェ",
      category: "カフェ",
      address: "ソウル市 城東区",
      latitude: 37.544,
      longitude: 127.055,
      arrivalAt: "13:00",
      leaveAt: "14:00",
      estimatedStayMinutes: 60,
      estimatedCost: 12000,
      reason: "静かなカフェという希望と一致します。",
      crowd: { level: "普通", scope: "area", areaName: "聖水駅一帯" },
      scoreBreakdown: { total: .86, preference: .95, crowd: .8, distance: .9, time: 1, budget: .85, diversity: .7 },
    },
    {
      id: "stop-2",
      order: 2,
      placeId: "place-2",
      placeName: "テストショップ",
      category: "ショッピング",
      latitude: 37.545,
      longitude: 127.056,
      arrivalAt: "14:20",
      leaveAt: "15:20",
      estimatedStayMinutes: 60,
      estimatedCost: null,
      reason: "セレクトショップの希望と一致します。",
      crowd: null,
      scoreBreakdown: { total: .79, preference: .9, crowd: .5, distance: .9, time: 1, budget: .7 },
    },
  ],
};
